### ISSUE TITLE
Login interfaces

### ISSUE THREAD

**Issue by skyarun** [MRobertsSL/UserLogin#8]
![php-login-form](https://cloud.githubusercontent.com/assets/15267525/13591708/3731ecb8-e511-11e5-9d25-cd6ddc20a714.png)

I just want to know can we arrange login interfaces like this as it is attractive.

**Comment by MRobertsSL** [comment]
Thanks Arun,
We have to use Bootsrap or something to create this... it just like a template.. you may try it...

Thanks

**Comment by MRobertsSL** [comment]
Thanks
